# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brother',
            fields=[
                ('brother_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('first_n', models.CharField(max_length=20)),
                ('last_n', models.CharField(max_length=20)),
                ('status', models.CharField(blank=True, choices=[('A', 'Active'), ('P', 'PLEDGE'), ('G', 'Alumni')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_n', models.CharField(max_length=30)),
                ('last_n', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('blacklisted', models.BooleanField(default=False)),
                ('host', models.ManyToManyField(to='list.Brother')),
            ],
        ),
    ]
