# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('P', 'PLEDGE'), ('G', 'Alumni')], max_length=1),
        ),
    ]
